name: Deploy

on:
  push:
    branches:
      - debs

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:

      RELEASE_KEY: ${{ secrets.RELEASE_KEY }}
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch the whole history

      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          path: .ci_scripts
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Checkout PPA's master
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ppa-stable
          path: .master
          ref: master
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Release
        run: .ci_scripts/ppa_maintanance/release.sh stable from-debs-branch

      - name: Push
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
